// frontend/src/admin/QiniuStorageSettings.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Alert, Button, Input, Select, Switch, message } from "antd"
import { CheckCircle2, CloudCog, KeyRound, ShieldCheck } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import { jsonMutation, requestJson } from "../api"

type QiniuConfig = {
  enabled: boolean; bucket: string; region: string; domain: string; object_prefix: string
  has_access_key: boolean; has_secret_key: boolean; credential_ready: boolean; available: boolean
  last_test_status?: string | null; last_test_message?: string | null; last_test_at?: string | null
}

const regionOptions = [
  { value: "z0", label: "华东" }, { value: "cn-east-2", label: "华东-浙江" },
  { value: "z1", label: "华北" }, { value: "z2", label: "华南" },
  { value: "na0", label: "北美" }, { value: "as0", label: "新加坡" },
]

export default function QiniuStorageSettings({ csrfToken }: { csrfToken: string }) {
  const queryClient = useQueryClient()
  const query = useQuery({
    queryKey: ["qiniu-provider"],
    queryFn: () => requestJson<QiniuConfig>("/api/admin/providers/qiniu"),
    refetchOnWindowFocus: false,
  })
  const [enabled, setEnabled] = useState(false)
  const [accessKey, setAccessKey] = useState("")
  const [secretKey, setSecretKey] = useState("")
  const [bucket, setBucket] = useState("")
  const [region, setRegion] = useState("z0")
  const [domain, setDomain] = useState("")
  const [objectPrefix, setObjectPrefix] = useState("zly-ai-video-studio/")
  const formLoaded = useRef(false)

  const applyConfig = (config: QiniuConfig) => {
    formLoaded.current = true
    setEnabled(config.enabled)
    setBucket(config.bucket)
    setRegion(config.region)
    setDomain(config.domain)
    setObjectPrefix(config.object_prefix)
    queryClient.setQueryData(["qiniu-provider"], config)
  }

  useEffect(() => {
    if (!query.data || formLoaded.current) return
    applyConfig(query.data)
  }, [query.data])

  const payload = () => ({
    enabled, access_key: accessKey || null, secret_key: secretKey || null, bucket, region, domain, object_prefix: objectPrefix,
  })
  const save = useMutation({
    mutationFn: () => requestJson<QiniuConfig>("/api/admin/providers/qiniu", jsonMutation(csrfToken, payload(), "PUT")),
    onSuccess: (config) => {
      setAccessKey("")
      setSecretKey("")
      applyConfig(config)
      message.success("七牛云存储配置已保存")
    },
  })
  const test = useMutation({
    mutationFn: () => requestJson<QiniuConfig>("/api/admin/providers/qiniu/test", jsonMutation(csrfToken, payload())),
    onSuccess: (config) => {
      queryClient.setQueryData<QiniuConfig>(["qiniu-provider"], (current) => current ? {
        ...current,
        last_test_status: config.last_test_status,
        last_test_message: config.last_test_message,
        last_test_at: config.last_test_at,
      } : config)
      message.success("七牛云连接测试成功")
    },
  })
  const error = query.error ?? save.error ?? test.error

  return (
    <main className="mx-auto max-w-[1020px] px-5 py-6 lg:px-8">
      <div className="flex items-start gap-4 border-b border-black/[0.06] pb-5">
        <span className="grid size-11 shrink-0 place-items-center rounded-xl bg-cyan-500/10 text-cyan-600">
          <CloudCog size={22} />
        </span>
        <div>
          <h2 className="text-base font-semibold text-[#111827]">七牛云媒体存储</h2>
          <p className="mt-1 text-xs leading-5 text-[#4b5563]">
            启用后，生成的图片和视频会先上传到七牛云，工作台以签名链接交付。
          </p>
        </div>
      </div>

      {!query.data?.credential_ready ? (
        <Alert
          className="mt-5"
          type="warning"
          showIcon
          message="凭证主密钥不可用"
          description="请先配置 ZLY_AI_VIDEO_STUDIO_CREDENTIAL_KEY；七牛云 AK/SK 会使用该密钥加密保存。"
        />
      ) : null}

      <section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
        <div className="rounded-2xl border border-black/[0.06] bg-white p-6 shadow-sm space-y-5">
          <div className="flex items-center justify-between gap-4 border-b border-black/[0.06] pb-4">
            <div>
              <p className="text-sm font-medium text-[#111827]">启用七牛云</p>
              <p className="mt-0.5 text-xs text-[#6b7280]">关闭后，新生成媒体继续使用当前本地交付方式；已存云端的作品不会删除。</p>
            </div>
            <Switch checked={enabled} onChange={setEnabled} />
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="block text-xs font-medium text-[#4b5563]">Access Key</label>
              <Input.Password
                className="mt-1.5"
                value={accessKey}
                onChange={(event) => setAccessKey(event.target.value)}
                prefix={<KeyRound size={15} className="text-[#9ca3af]" />}
                placeholder={query.data?.has_access_key ? "已保存，留空不修改" : "输入 Access Key"}
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-[#4b5563]">Secret Key</label>
              <Input.Password
                className="mt-1.5"
                value={secretKey}
                onChange={(event) => setSecretKey(event.target.value)}
                prefix={<KeyRound size={15} className="text-[#9ca3af]" />}
                placeholder={query.data?.has_secret_key ? "已保存，留空不修改" : "输入 Secret Key"}
              />
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="block text-xs font-medium text-[#4b5563]">Bucket</label>
              <Input
                className="mt-1.5"
                value={bucket}
                onChange={(event) => setBucket(event.target.value)}
                placeholder="your-bucket"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-[#4b5563]">存储区域</label>
              <Select
                className="mt-1.5 w-full"
                value={region}
                onChange={setRegion}
                options={regionOptions}
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-medium text-[#4b5563]">访问域名</label>
            <Input
              className="mt-1.5"
              value={domain}
              onChange={(event) => setDomain(event.target.value)}
              placeholder="https://media.example.com"
            />
          </div>

          <div>
            <label className="block text-xs font-medium text-[#4b5563]">对象前缀</label>
            <Input
              className="mt-1.5"
              value={objectPrefix}
              onChange={(event) => setObjectPrefix(event.target.value)}
              placeholder="zly-ai-video-studio/"
            />
          </div>

          {error ? <Alert type="error" showIcon message={error.message} /> : null}

          <div className="flex flex-wrap gap-3 pt-2">
            <Button type="primary" loading={save.isPending} onClick={() => save.mutate()}>
              保存配置
            </Button>
            <Button loading={test.isPending} onClick={() => test.mutate()} icon={<CheckCircle2 size={15} />}>
              测试连接
            </Button>
          </div>
        </div>

        <aside className="rounded-2xl border border-black/[0.06] bg-white p-6 shadow-sm flex flex-col justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-[#6b7280]">当前状态</p>
            <p className={`mt-3 text-sm font-semibold ${query.data?.available ? "text-emerald-600" : "text-amber-600"}`}>
              {query.data?.available ? "● 新媒体将上传到七牛云" : "● 仍使用本地交付"}
            </p>

            <dl className="mt-6 space-y-4 text-xs">
              <div>
                <dt className="text-[#6b7280]">配置密钥</dt>
                <dd className="mt-1 font-medium text-[#111827]">
                  {query.data?.has_access_key && query.data?.has_secret_key ? "已保存" : "尚未完整配置"}
                </dd>
              </div>
              <div>
                <dt className="text-[#6b7280]">最近测试</dt>
                <dd className="mt-1 font-medium break-words text-[#111827]">
                  {query.data?.last_test_status
                    ? `${query.data.last_test_status} · ${query.data.last_test_at ? new Date(query.data.last_test_at).toLocaleString("zh-CN", { hour12: false }) : ""}`
                    : "尚未测试"}
                </dd>
              </div>
              {query.data?.last_test_message ? (
                <div>
                  <dt className="text-[#6b7280]">测试结果</dt>
                  <dd className="mt-1 break-words text-[11px] text-[#6b7280]">{query.data.last_test_message}</dd>
                </div>
              ) : null}
            </dl>
          </div>

          <div className="mt-6 flex gap-2 rounded-xl bg-[#f9fafb] border border-black/[0.06] p-3 text-xs leading-5 text-[#6b7280]">
            <ShieldCheck size={16} className="mt-0.5 shrink-0 text-[#7047f6]" />
            <span>AK/SK 不会回显，保存时留空即可保留已配置的密钥。</span>
          </div>
        </aside>
      </section>
    </main>
  )
}

// z-admin/src/views/settings/QiniuStorageSettings.vue
<template>
  <div class="qiniu-settings-card">
    <div class="card-header">
      <div class="icon-badge qiniu-badge">
        <CloudCog :size="22" />
      </div>
      <div>
        <h2 class="title">七牛云对象存储 (Kodo)</h2>
        <p class="desc">
          启用后，创作台生成的所有高质量原图与高清成片将自动同步至云端对象存储，并生成高速 CDN 分发链接。
        </p>
      </div>
    </div>

    <div class="card-body">
      <div class="settings-grid">
        <div class="form-col">
          <!-- 启用开关 -->
          <div class="form-item row-item">
            <div>
              <span class="form-label">启用七牛云媒体存储</span>
              <p class="form-sub">开启后媒体资源由云端托管，关闭则保留本地输出</p>
            </div>
            <a-switch v-model:checked="enabled" />
          </div>

          <!-- Access Key -->
          <div class="form-item">
            <label class="form-label">Access Key (AK)</label>
            <a-input-password
              v-model:value="accessKey"
              :placeholder="config?.has_access_key ? '已配置 Access Key (留空保持不变)' : '请输入七牛云 AK'"
            />
          </div>

          <!-- Secret Key -->
          <div class="form-item">
            <label class="form-label">Secret Key (SK)</label>
            <a-input-password
              v-model:value="secretKey"
              :placeholder="config?.has_secret_key ? '已配置 Secret Key (留空保持不变)' : '请输入七牛云 SK'"
            />
          </div>

          <!-- Bucket & Region -->
          <div class="grid-row">
            <div class="form-item">
              <label class="form-label">存储空间名称 (Bucket)</label>
              <a-input v-model:value="bucket" placeholder="例如：my-ai-media" />
            </div>
            <div class="form-item">
              <label class="form-label">存储区域 (Region)</label>
              <a-select v-model:value="region" :options="regionOptions" />
            </div>
          </div>

          <!-- CDN Domain -->
          <div class="form-item">
            <label class="form-label">访问域名 (带 https:// 前缀)</label>
            <a-input v-model:value="domain" placeholder="https://cdn.your-domain.com" />
            <span class="help-text">
              七牛云空间绑定的自定义 CDN 域名或测试域名，必须带协议头且末尾不加斜杠。
            </span>
          </div>

          <!-- Object Prefix -->
          <div class="form-item">
            <label class="form-label">资源前缀目录 (Object Prefix)</label>
            <a-input v-model:value="objectPrefix" placeholder="zly-ai-video-studio/" />
          </div>

          <div v-if="errorMsg" class="form-item">
            <a-alert type="error" show-icon :message="errorMsg" />
          </div>

          <div class="form-actions">
            <a-button type="primary" :loading="saving" @click="handleSave">
              保存存储配置
            </a-button>
            <a-button :loading="testing" @click="handleTest">
              <template #icon><CheckCircle2 :size="15" /></template>
              测试读写连接
            </a-button>
          </div>
        </div>

        <!-- 状态与提示面板 -->
        <div class="status-col">
          <div class="status-panel">
            <p class="status-title">存储读写验证</p>
            <p class="status-badge" :class="statusClass">
              <span class="status-dot"></span>
              {{ statusLabel }}
            </p>
            <p v-if="config?.last_test_message" class="status-msg">
              {{ config.last_test_message }}
            </p>
            <p class="status-time">
              {{ config?.last_test_at ? new Date(config.last_test_at).toLocaleString('zh-CN', { hour12: false }) : '未执行测试' }}
            </p>
          </div>

          <div class="tips-panel mt-3">
            <p class="tips-title">存储使用说明</p>
            <ul class="tips-list">
              <li>AK 与 SK 在服务器端使用对称密钥 <b>加密存储</b>，绝不泄露明文。</li>
              <li>测试连接会自动上传一个探测文件并立刻删除，校验完整的写与删权限。</li>
              <li>如需测试域名，可在七牛云控制台进入对应存储空间「空间概览」中查看。</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import { CloudCog, CheckCircle2 } from 'lucide-vue-next'
import {
  getQiniuConfig,
  updateQiniuConfig,
  testQiniuConnection,
} from '../../api/providers'

const regionOptions = [
  { value: 'z0', label: '华东 (z0)' },
  { value: 'cn-east-2', label: '华东-浙江 (cn-east-2)' },
  { value: 'z1', label: '华北 (z1)' },
  { value: 'z2', label: '华南 (z2)' },
  { value: 'na0', label: '北美 (na0)' },
  { value: 'as0', label: '新加坡 (as0)' },
]

const config = ref(null)
const enabled = ref(false)
const accessKey = ref('')
const secretKey = ref('')
const bucket = ref('')
const region = ref('z0')
const domain = ref('')
const objectPrefix = ref('zly-ai-video-studio/')

const saving = ref(false)
const testing = ref(false)
const errorMsg = ref(null)

const statusClass = computed(() => {
  if (config.value?.last_test_status === 'success') return 'status-success'
  if (config.value?.last_test_status === 'failed') return 'status-failed'
  return 'status-idle'
})

const statusLabel = computed(() => {
  if (config.value?.last_test_status === 'success') return '读写正常'
  if (config.value?.last_test_status === 'failed') return '连接失败'
  return '尚未测试'
})

const loadConfig = async () => {
  try {
    const data = await getQiniuConfig()
    config.value = data
    enabled.value = data.enabled
    bucket.value = data.bucket
    region.value = data.region || 'z0'
    domain.value = data.domain
    objectPrefix.value = data.object_prefix || 'zly-ai-video-studio/'
  } catch (err) {
    errorMsg.value = err?.response?.data?.detail || err.message || '加载存储配置失败'
  }
}

const handleSave = async () => {
  errorMsg.value = null
  saving.value = true
  try {
    const updated = await updateQiniuConfig({
      enabled: enabled.value,
      access_key: accessKey.value || null,
      secret_key: secretKey.value || null,
      bucket: bucket.value,
      region: region.value,
      domain: domain.value,
      object_prefix: objectPrefix.value,
    })
    config.value = updated
    accessKey.value = ''
    secretKey.value = ''
    message.success('七牛云存储配置已保存')
  } catch (err) {
    errorMsg.value = err?.response?.data?.detail || err.message || '保存失败'
  } finally {
    saving.value = false
  }
}

const handleTest = async () => {
  errorMsg.value = null
  testing.value = true
  try {
    const updated = await testQiniuConnection({
      access_key: accessKey.value || null,
      secret_key: secretKey.value || null,
      bucket: bucket.value,
      region: region.value,
      domain: domain.value,
      object_prefix: objectPrefix.value,
    })
    config.value = updated
    message.success('七牛云存储读写测试成功！')
  } catch (err) {
    errorMsg.value = err?.response?.data?.detail || err.message || '测试失败'
    await loadConfig()
  } finally {
    testing.value = false
  }
}

onMounted(() => {
  loadConfig()
})
</script>

<style scoped>
.qiniu-settings-card {
  background: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.06);
  border-radius: 16px;
  padding: 24px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.03);
}

.card-header {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.06);
  padding-bottom: 20px;
}

.icon-badge {
  width: 44px;
  height: 44px;
  border-radius: 12px;
  display: grid;
  place-items: center;
  flex-shrink: 0;
}

.qiniu-badge {
  background: rgba(6, 182, 212, 0.1);
  color: #0891b2;
}

.title {
  font-size: 16px;
  font-weight: 600;
  color: #111827;
  margin: 0;
}

.desc {
  margin: 4px 0 0;
  font-size: 13px;
  line-height: 20px;
  color: #4b5563;
}

.card-body {
  margin-top: 20px;
}

.settings-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 280px;
  gap: 24px;
}

@media (max-width: 768px) {
  .settings-grid {
    grid-template-columns: 1fr;
  }
}

.form-col {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.form-item {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.grid-row {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}

.row-item {
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  padding: 8px 0;
}

.form-label {
  font-size: 13px;
  font-weight: 500;
  color: #4b5563;
}

.form-sub {
  font-size: 12px;
  color: #9ca3af;
  margin: 2px 0 0;
}

.help-text {
  font-size: 12px;
  color: #6b7280;
}

.form-actions {
  display: flex;
  gap: 12px;
  padding-top: 8px;
}

.status-panel, .tips-panel {
  background: #f9fafb;
  border: 1px solid rgba(0, 0, 0, 0.06);
  border-radius: 12px;
  padding: 16px;
}

.status-title, .tips-title {
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: #6b7280;
  margin: 0 0 12px;
}

.status-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 14px;
  font-weight: 600;
  margin: 0 0 8px;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: currentColor;
}

.status-success {
  color: #059669;
}

.status-failed {
  color: #dc2626;
}

.status-idle {
  color: #6b7280;
}

.status-msg {
  font-size: 12px;
  line-height: 18px;
  color: #4b5563;
  margin: 0 0 10px;
}

.status-time {
  font-size: 12px;
  color: #9ca3af;
  margin: 0;
}

.tips-list {
  margin: 0;
  padding-left: 16px;
  font-size: 12px;
  line-height: 20px;
  color: #6b7280;
}

.mt-3 {
  margin-top: 12px;
}
</style>
