// z-admin/src/views/settings/GrsProviderSettings.vue
<template>
  <div class="grs-settings-card">
    <div class="card-header">
      <div class="icon-badge grs-badge">
        <Cloud :size="22" />
      </div>
      <div>
        <h2 class="title">GRS 极速生图供应商</h2>
        <p class="desc">
          提供 NanoBanana、FLUX 等极速画质大模型，用于人物、场景与分镜资产快速生成。
        </p>
      </div>
    </div>

    <div class="card-body">
      <!-- 基础配置 -->
      <div class="settings-grid">
        <div class="form-col">
          <div class="form-item row-item">
            <div>
              <span class="form-label">启用 GRS 服务</span>
              <p class="form-sub">开启后系统可调用 GRS 进行云端文生图与图生图</p>
            </div>
            <a-switch v-model:checked="enabled" />
          </div>

          <div class="form-item">
            <label class="form-label">Base URL (API 服务地址)</label>
            <a-input v-model:value="baseUrl" placeholder="https://grsai.dakka.com.cn" />
          </div>

          <div class="form-item">
            <label class="form-label">API Key / Token</label>
            <a-input-password
              v-model:value="apiKey"
              :placeholder="config?.has_api_key ? (config.api_key_masked || '已配置密钥 (留空保持不变)') : '请输入 GRS API Key'"
            />
            <span v-if="config?.has_api_key" class="help-text text-success">
              已安全加密存储，再次保存如留空则保留原密钥。
            </span>
          </div>

          <div class="form-item">
            <label class="form-label">分镜生图最大并发数</label>
            <a-input-number v-model:value="maxStoryboardConcurrency" :min="1" :max="20" :precision="0" />
            <span class="help-text">草图和渲染图共用该并发上限，默认 5。</span>
          </div>

          <div v-if="errorMsg" class="form-item">
            <a-alert type="error" show-icon :message="errorMsg" />
          </div>

          <div class="form-actions">
            <a-button type="primary" :loading="saving" @click="handleSave">
              保存供应商配置
            </a-button>
            <a-button :loading="testing" @click="handleTest">
              <template #icon><CheckCircle2 :size="15" /></template>
              测试连接
            </a-button>
          </div>
        </div>

        <!-- 余额与状态面板 -->
        <div class="status-col">
          <div class="balance-panel">
            <div class="panel-header">
              <span class="panel-title">账户点数余额</span>
              <a-button type="link" size="small" :loading="refreshingBalance" @click="handleRefreshBalance">
                <template #icon><RefreshCw :size="13" /></template>
                刷新
              </a-button>
            </div>
            <div class="balance-value">
              {{ config?.last_balance != null ? config.last_balance.toLocaleString() : '--' }}
              <span class="balance-unit">点</span>
            </div>
            <p class="panel-time">
              {{ config?.last_balance_at ? `更新于 ${new Date(config.last_balance_at).toLocaleTimeString()}` : '点击测试或刷新获取' }}
            </p>
          </div>

          <div class="status-panel mt-3">
            <p class="status-title">连通性状态</p>
            <p class="status-badge" :class="statusClass">
              <span class="status-dot"></span>
              {{ statusLabel }}
            </p>
            <p v-if="config?.last_test_message" class="status-msg">
              {{ config.last_test_message }}
            </p>
            <p class="status-time">
              {{ config?.last_test_at ? new Date(config.last_test_at).toLocaleString('zh-CN', { hour12: false }) : '未执行测试' }}
            </p>
          </div>
        </div>
      </div>

      <!-- 生图模型目录 -->
      <div class="models-section">
        <div class="section-header">
          <div>
            <h3 class="section-title">生图模型目录</h3>
            <p class="section-desc">管理可用于创作台画面的生图模型通道与默认选择。</p>
          </div>
          <div class="section-actions">
            <a-button type="primary" ghost @click="addModalVisible = true">
              <template #icon><Plus :size="15" /></template>
              新增模型
            </a-button>
            <a-button :loading="savingModels" @click="handleSaveModels">
              保存模型调整
            </a-button>
          </div>
        </div>

        <a-table
          :data-source="models"
          :columns="columns"
          row-key="workflow_id"
          :pagination="false"
          size="middle"
          class="models-table"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'display_name'">
              <div>
                <span class="font-medium">{{ record.display_name }}</span>
                <p class="text-xs text-gray-500 m-0">{{ record.provider_model }}</p>
              </div>
            </template>
            <template v-else-if="column.key === 'profile'">
              <a-tag color="purple">{{ getProfileLabel(record.profile) }}</a-tag>
            </template>
            <template v-else-if="column.key === 'enabled'">
              <a-switch v-model:checked="record.enabled" size="small" />
            </template>
            <template v-else-if="column.key === 'is_default'">
              <a-radio :checked="record.is_default" @click="handleSetDefault(record)">
                默认
              </a-radio>
            </template>
          </template>
        </a-table>
      </div>
    </div>

    <!-- 新增模型弹窗 -->
    <a-modal
      v-model:open="addModalVisible"
      title="新增 GRS 生图模型"
      ok-text="确认添加并保存"
      cancel-text="取消"
      @ok="handleCreateModel"
    >
      <div class="modal-form">
        <div class="form-item">
          <label class="form-label">模型标识 (Provider Model)</label>
          <a-input v-model:value="newModel.provider_model" placeholder="例如：flux-dev, gpt-image-3" />
        </div>
        <div class="form-item">
          <label class="form-label">显示名称</label>
          <a-input v-model:value="newModel.display_name" placeholder="例如：FLUX 高清真实写实" />
        </div>
        <div class="form-item">
          <label class="form-label">模型类型 (Profile)</label>
          <a-select v-model:value="newModel.profile" :options="profiles" />
        </div>
        <div class="form-item">
          <label class="form-label">模型说明</label>
          <a-input v-model:value="newModel.description" placeholder="用途或特点说明" />
        </div>
      </div>
    </a-modal>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import { Cloud, CheckCircle2, RefreshCw, Plus } from 'lucide-vue-next'
import {
  getGrsConfig,
  updateGrsConfig,
  testGrsConnection,
  queryGrsBalance,
  getGrsModels,
  updateGrsModels,
  createGrsModel,
} from '../../api/providers'

const config = ref(null)
const enabled = ref(false)
const baseUrl = ref('https://grsai.dakka.com.cn')
const apiKey = ref('')
const maxStoryboardConcurrency = ref(5)
const models = ref([])
const profiles = ref([])

const saving = ref(false)
const testing = ref(false)
const refreshingBalance = ref(false)
const savingModels = ref(false)
const errorMsg = ref(null)

const addModalVisible = ref(false)
const newModel = ref({
  provider_model: '',
  display_name: '',
  profile: 'nano_banana',
  description: '',
})

const columns = [
  { title: '模型名称', key: 'display_name' },
  { title: '规格类型', key: 'profile', width: 220 },
  { title: '状态', key: 'enabled', width: 90 },
  { title: '默认模型', key: 'is_default', width: 100 },
]

const statusClass = computed(() => {
  if (config.value?.last_test_status === 'success') return 'status-success'
  if (config.value?.last_test_status === 'failed') return 'status-failed'
  return 'status-idle'
})

const statusLabel = computed(() => {
  if (config.value?.last_test_status === 'success') return '已连通'
  if (config.value?.last_test_status === 'failed') return '连接失败'
  return '尚未测试'
})

const getProfileLabel = (p) => {
  const item = profiles.value.find(i => i.value === p)
  return item?.label || p
}

const loadData = async () => {
  try {
    const [cfg, modelsData] = await Promise.all([getGrsConfig(), getGrsModels()])
    config.value = cfg
    enabled.value = cfg.enabled
    baseUrl.value = cfg.base_url
    maxStoryboardConcurrency.value = cfg.max_storyboard_concurrency || 5
    models.value = modelsData.models
    profiles.value = modelsData.profiles
  } catch (err) {
    errorMsg.value = err?.response?.data?.detail || err.message || '加载 GRS 配置失败'
  }
}

const handleSave = async () => {
  errorMsg.value = null
  saving.value = true
  try {
    const updated = await updateGrsConfig({
      enabled: enabled.value,
      base_url: baseUrl.value,
      api_key: apiKey.value || null,
      max_storyboard_concurrency: maxStoryboardConcurrency.value,
    })
    config.value = updated
    apiKey.value = ''
    message.success('GRS 配置已保存')
  } catch (err) {
    errorMsg.value = err?.response?.data?.detail || err.message || '保存失败'
  } finally {
    saving.value = false
  }
}

const handleTest = async () => {
  errorMsg.value = null
  testing.value = true
  try {
    const updated = await testGrsConnection({
      base_url: baseUrl.value,
      api_key: apiKey.value || null,
    })
    config.value = updated
    message.success(`连接测试成功，当前点数: ${updated.last_balance}`)
  } catch (err) {
    errorMsg.value = err?.response?.data?.detail || err.message || '测试失败'
    await loadData()
  } finally {
    testing.value = false
  }
}

const handleRefreshBalance = async () => {
  refreshingBalance.value = true
  try {
    const res = await queryGrsBalance()
    if (res.error) {
      message.error(res.error)
    } else {
      if (config.value) {
        config.value.last_balance = res.credits
        config.value.last_balance_at = res.queried_at
      }
      message.success(`余额已更新: ${res.credits} 点`)
    }
  } catch (err) {
    message.error(err?.response?.data?.detail || err.message || '刷新余额失败')
  } finally {
    refreshingBalance.value = false
  }
}

const handleSetDefault = (record) => {
  models.value.forEach(m => {
    m.is_default = m.workflow_id === record.workflow_id
  })
}

const handleSaveModels = async () => {
  savingModels.value = true
  try {
    const res = await updateGrsModels(models.value)
    models.value = res.models
    message.success('生图模型配置已保存')
  } catch (err) {
    message.error(err?.response?.data?.detail || err.message || '模型更新失败')
  } finally {
    savingModels.value = false
  }
}

const handleCreateModel = async () => {
  if (!newModel.value.provider_model || !newModel.value.display_name) {
    message.warning('请填写模型标识和显示名称')
    return
  }
  try {
    const res = await createGrsModel(newModel.value)
    models.value = res.models
    addModalVisible.value = false
    newModel.value = { provider_model: '', display_name: '', profile: 'nano_banana', description: '' }
    message.success('模型已添加并保存')
  } catch (err) {
    message.error(err?.response?.data?.detail || err.message || '创建模型失败')
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.grs-settings-card {
  background: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.06);
  border-radius: 16px;
  padding: 24px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.03);
  margin-top: 20px;
}

.card-header {
  display: flex;
  align-items: flex-start;
  gap: 16px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.06);
  padding-bottom: 20px;
}

.icon-badge {
  width: 44px;
  height: 44px;
  border-radius: 12px;
  display: grid;
  place-items: center;
  flex-shrink: 0;
}

.grs-badge {
  background: rgba(14, 165, 233, 0.1);
  color: #0ea5e9;
}

.title {
  font-size: 16px;
  font-weight: 600;
  color: #111827;
  margin: 0;
}

.desc {
  margin: 4px 0 0;
  font-size: 13px;
  line-height: 20px;
  color: #4b5563;
}

.card-body {
  margin-top: 20px;
}

.settings-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 280px;
  gap: 24px;
}

@media (max-width: 768px) {
  .settings-grid {
    grid-template-columns: 1fr;
  }
}

.form-col {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.form-item {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.row-item {
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  padding: 8px 0;
}

.form-label {
  font-size: 13px;
  font-weight: 500;
  color: #4b5563;
}

.form-sub {
  font-size: 12px;
  color: #9ca3af;
  margin: 2px 0 0;
}

.help-text {
  font-size: 12px;
}

.text-success {
  color: #059669;
}

.form-actions {
  display: flex;
  gap: 12px;
  padding-top: 8px;
}

.balance-panel {
  background: linear-gradient(135deg, rgba(14, 165, 233, 0.05), rgba(99, 102, 241, 0.05));
  border: 1px solid rgba(14, 165, 233, 0.15);
  border-radius: 12px;
  padding: 16px;
}

.panel-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.panel-title {
  font-size: 12px;
  font-weight: 600;
  color: #0284c7;
}

.balance-value {
  font-size: 28px;
  font-weight: 700;
  color: #0369a1;
  margin: 8px 0 4px;
}

.balance-unit {
  font-size: 14px;
  font-weight: normal;
  color: #64748b;
  margin-left: 4px;
}

.panel-time {
  font-size: 11px;
  color: #94a3b8;
  margin: 0;
}

.status-panel {
  background: #f9fafb;
  border: 1px solid rgba(0, 0, 0, 0.06);
  border-radius: 12px;
  padding: 16px;
}

.status-title {
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: #6b7280;
  margin: 0 0 12px;
}

.status-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  font-size: 14px;
  font-weight: 600;
  margin: 0 0 8px;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: currentColor;
}

.status-success {
  color: #059669;
}

.status-failed {
  color: #dc2626;
}

.status-idle {
  color: #6b7280;
}

.status-msg {
  font-size: 12px;
  line-height: 18px;
  color: #4b5563;
  margin: 0 0 10px;
}

.status-time {
  font-size: 12px;
  color: #9ca3af;
  margin: 0;
}

.models-section {
  margin-top: 32px;
  border-top: 1px solid rgba(0, 0, 0, 0.06);
  padding-top: 24px;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  padding: 0 8px;
}

.section-title {
  font-size: 15px;
  font-weight: 600;
  color: #111827;
  margin: 0;
}

.section-desc {
  font-size: 12px;
  color: #6b7280;
  margin: 2px 0 0;
}

.section-actions {
  display: flex;
  gap: 10px;
}

.models-table {
  background: #ffffff;
  border-radius: 8px;
  border: 1px solid rgba(0, 0, 0, 0.06);
}

.modal-form {
  display: flex;
  flex-direction: column;
  gap: 14px;
  padding-top: 12px;
}

.mt-3 {
  margin-top: 12px;
}
</style>

// frontend/src/admin/GrsProviderSettings.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Alert, Button, Input, Modal, Select, Switch, Table, Tag, message } from "antd"
import { CheckCircle2, Cloud, KeyRound, Plus, RefreshCw, WalletCards } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { jsonMutation, requestJson } from "../api"

type ProviderConfig = {
  enabled: boolean
  base_url: string
  api_key_masked?: string | null
  has_api_key: boolean
  credential_ready: boolean
  last_test_status?: string | null
  last_test_message?: string | null
  last_test_at?: string | null
  last_balance?: number | null
  last_balance_at?: string | null
  available: boolean
  unavailable_reason?: string | null
}

type CatalogModel = {
  workflow_id: string
  provider_model: string
  display_name: string
  description: string
  profile: string
  resolutions: string[] | null
  enabled: boolean
  sort_order: number
  is_default: boolean
  builtin: boolean
}

type CatalogPayload = {
  models: CatalogModel[]
  profiles: { value: string; label: string }[]
}

export default function GrsProviderSettings({ csrfToken }: { csrfToken: string }) {
  const queryClient = useQueryClient()
  const query = useQuery({ queryKey: ["grs-provider"], queryFn: () => requestJson<ProviderConfig>("/api/admin/providers/grs") })
  const catalogQuery = useQuery({
    queryKey: ["grs-image-models"],
    queryFn: () => requestJson<CatalogPayload>("/api/admin/providers/grs/models"),
  })
  const [enabled, setEnabled] = useState(false)
  const [baseUrl, setBaseUrl] = useState("https://grsai.dakka.com.cn")
  const [apiKey, setApiKey] = useState("")
  const [models, setModels] = useState<CatalogModel[]>([])
  const [addOpen, setAddOpen] = useState(false)
  const [newModelId, setNewModelId] = useState("")
  const [newDisplayName, setNewDisplayName] = useState("")
  const [newProfile, setNewProfile] = useState("nano_banana")

  useEffect(() => {
    if (!query.data) return
    setEnabled(query.data.enabled)
    setBaseUrl(query.data.base_url)
  }, [query.data])

  useEffect(() => {
    if (catalogQuery.data) setModels(catalogQuery.data.models)
  }, [catalogQuery.data])

  const profileLabel = useMemo(() => {
    const mapping = new Map((catalogQuery.data?.profiles ?? []).map((item) => [item.value, item.label]))
    return (profile: string) => mapping.get(profile) || profile
  }, [catalogQuery.data])

  const refresh = () => {
    queryClient.invalidateQueries({ queryKey: ["grs-provider"] })
    queryClient.invalidateQueries({ queryKey: ["grs-image-models"] })
  }
  const save = useMutation({
    mutationFn: () => requestJson<ProviderConfig>("/api/admin/providers/grs", jsonMutation(csrfToken, {
      enabled, base_url: baseUrl, api_key: apiKey || null,
    }, "PUT")),
    onSuccess: () => {
      setApiKey("")
      refresh()
      message.success("GRS 图片供应商配置已保存")
    },
  })
  const saveModels = useMutation({
    mutationFn: (next: CatalogModel[]) => requestJson<CatalogPayload>("/api/admin/providers/grs/models", jsonMutation(csrfToken, {
      models: next.map((item) => ({
        workflow_id: item.workflow_id,
        display_name: item.display_name,
        enabled: item.enabled,
        sort_order: item.sort_order,
        is_default: item.is_default,
      })),
    }, "PUT")),
    onSuccess: (payload) => {
      setModels(payload.models)
      queryClient.invalidateQueries({ queryKey: ["grs-image-models"] })
      message.success("生图模型目录已保存")
    },
  })
  const addModel = useMutation({
    mutationFn: () => requestJson<CatalogPayload>("/api/admin/providers/grs/models", jsonMutation(csrfToken, {
      provider_model: newModelId.trim(),
      display_name: newDisplayName.trim() || newModelId.trim(),
      profile: newProfile,
      enabled: true,
    })),
    onSuccess: (payload) => {
      setModels(payload.models)
      setAddOpen(false)
      setNewModelId("")
      setNewDisplayName("")
      queryClient.invalidateQueries({ queryKey: ["grs-image-models"] })
      message.success("已添加生图模型")
    },
  })
  const syncCatalog = useMutation({
    mutationFn: () => requestJson<CatalogPayload>("/api/admin/providers/grs/models/sync", {
      method: "POST",
      headers: { "X-CSRF-Token": csrfToken },
    }),
    onSuccess: (payload) => {
      setModels(payload.models)
      queryClient.invalidateQueries({ queryKey: ["grs-image-models"] })
      message.success("已同步内置目录中缺失的模型")
    },
  })
  const test = useMutation({
    mutationFn: () => requestJson<ProviderConfig>("/api/admin/providers/grs/test", jsonMutation(csrfToken, {
      base_url: baseUrl,
      api_key: apiKey || null,
    })),
    onSuccess: () => {
      refresh()
      message.success("GRS 连接测试成功")
    },
  })
  const balance = useMutation({
    mutationFn: () => requestJson<{ credits: number }>("/api/admin/providers/grs/balance", { method: "POST", headers: { "X-CSRF-Token": csrfToken } }),
    onSuccess: () => {
      refresh()
      message.success("上游余额查询成功")
    },
  })
  const error = save.error ?? saveModels.error ?? addModel.error ?? syncCatalog.error ?? test.error ?? balance.error ?? query.error ?? catalogQuery.error

  const updateModel = (workflowId: string, patch: Partial<CatalogModel>) => {
    setModels((current) => current.map((item) => {
      if (item.workflow_id !== workflowId) {
        return patch.is_default ? { ...item, is_default: false } : item
      }
      return { ...item, ...patch }
    }))
  }

  return (
    <main className="mx-auto max-w-[1020px] px-5 py-6 lg:px-8">
      <div className="flex items-start gap-4 border-b border-black/[0.06] pb-5">
        <span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#7047f6]/10 text-[#7047f6]">
          <Cloud size={22} />
        </span>
        <div>
          <h2 className="text-base font-semibold text-[#111827]">GRS 图片供应商</h2>
          <p className="mt-1 text-xs leading-5 text-[#4b5563]">
            单一主配置负责连接与余额；启用的模型会作为独立工作流出现在创作页。
          </p>
        </div>
      </div>

      {!query.data?.credential_ready ? (
        <Alert
          className="mt-5"
          type="warning"
          showIcon
          message="凭证主密钥不可用"
          description="请在部署环境设置 ZLY_AI_VIDEO_STUDIO_CREDENTIAL_KEY。视频功能不受影响，图片提交会保持锁定。"
        />
      ) : null}

      <section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
        <div className="rounded-2xl border border-black/[0.06] bg-white p-6 shadow-sm space-y-5">
          <div className="flex items-center justify-between gap-4 border-b border-black/[0.06] pb-4">
            <div>
              <p className="text-sm font-medium text-[#111827]">启用 GRS 生图</p>
              <p className="mt-0.5 text-xs text-[#6b7280]">关闭后仍保留图片入口和历史，只锁定提交。</p>
            </div>
            <Switch checked={enabled} onChange={setEnabled} />
          </div>

          <div>
            <label className="block text-xs font-medium text-[#4b5563]">Base URL</label>
            <Input
              className="mt-1.5"
              value={baseUrl}
              onChange={(event) => setBaseUrl(event.target.value)}
              placeholder="https://grsai.dakka.com.cn"
            />
          </div>

          <div>
            <label className="block text-xs font-medium text-[#4b5563]">API Key</label>
            <Input.Password
              className="mt-1.5"
              value={apiKey}
              onChange={(event) => setApiKey(event.target.value)}
              prefix={<KeyRound size={15} className="text-[#9ca3af]" />}
              placeholder={query.data?.api_key_masked || "输入新的 API Key"}
            />
          </div>

          {error ? <Alert type="error" showIcon message={error.message} /> : null}

          <div className="flex flex-wrap gap-3 pt-2">
            <Button type="primary" loading={save.isPending} onClick={() => save.mutate()}>
              保存配置
            </Button>
            <Button loading={test.isPending} onClick={() => test.mutate()} icon={<CheckCircle2 size={15} />}>
              测试连接
            </Button>
            <Button loading={balance.isPending} onClick={() => balance.mutate()} icon={<WalletCards size={15} />}>
              查询余额
            </Button>
          </div>
        </div>

        <aside className="rounded-2xl border border-black/[0.06] bg-white p-6 shadow-sm">
          <p className="text-xs font-semibold uppercase tracking-wider text-[#6b7280]">当前状态</p>
          <p className={`mt-3 text-sm font-semibold ${query.data?.available ? "text-emerald-600" : "text-amber-600"}`}>
            {query.data?.available ? "● 可以提交图片任务" : "● 图片提交已锁定"}
          </p>
          {query.data?.unavailable_reason ? (
            <p className="mt-2 text-xs leading-5 text-[#6b7280]">{query.data.unavailable_reason}</p>
          ) : null}

          <dl className="mt-6 space-y-4 text-xs">
            <div>
              <dt className="text-[#6b7280]">最近测试</dt>
              <dd className="mt-1 font-medium text-[#111827]">
                {query.data?.last_test_status
                  ? `${query.data.last_test_status} · ${query.data.last_test_at ? new Date(query.data.last_test_at).toLocaleString("zh-CN", { hour12: false }) : ""}`
                  : "尚未测试"}
              </dd>
            </div>
            <div>
              <dt className="text-[#6b7280]">上游余额</dt>
              <dd className="mt-1 font-mono font-medium text-[#111827]">
                {query.data?.last_balance !== undefined && query.data?.last_balance !== null
                  ? `${query.data.last_balance} 点`
                  : "尚未查询"}
              </dd>
            </div>
            <div>
              <dt className="text-[#6b7280]">已启用模型</dt>
              <dd className="mt-1 font-medium text-[#111827]">{models.filter((item) => item.enabled).length} 个</dd>
            </div>
          </dl>
        </aside>
      </section>

      <section className="mt-6 rounded-2xl border border-black/[0.06] bg-white p-6 shadow-sm">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h3 className="text-sm font-semibold text-[#111827]">生图模型目录</h3>
            <p className="mt-1 text-xs leading-5 text-[#6b7280]">
              勾选启用后会出现在创作页「选择工作流」。内置目录来自 GRS 文档，不会自动拉取上游列表。
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button icon={<Plus size={14} />} onClick={() => setAddOpen(true)}>添加模型</Button>
            <Button icon={<RefreshCw size={14} />} loading={syncCatalog.isPending} onClick={() => syncCatalog.mutate()}>
              同步内置目录
            </Button>
            <Button type="primary" loading={saveModels.isPending} onClick={() => saveModels.mutate(models)}>
              保存目录
            </Button>
          </div>
        </div>

        <Table
          className="mt-4"
          rowKey="workflow_id"
          size="middle"
          pagination={false}
          dataSource={models}
          columns={[
            {
              title: "启用",
              dataIndex: "enabled",
              width: 72,
              render: (_, record) => (
                <Switch checked={record.enabled} onChange={(checked) => updateModel(record.workflow_id, { enabled: checked })} />
              ),
            },
            {
              title: "显示名",
              dataIndex: "display_name",
              render: (_, record) => (
                <Input
                  value={record.display_name}
                  onChange={(event) => updateModel(record.workflow_id, { display_name: event.target.value })}
                />
              ),
            },
            {
              title: "上游模型 ID",
              dataIndex: "provider_model",
              render: (value: string, record) => (
                <span className="font-mono text-xs text-[#1f2937]">
                  {value}
                  {record.builtin ? <Tag className="ml-2" color="default">内置</Tag> : <Tag className="ml-2">自定义</Tag>}
                </span>
              ),
            },
            {
              title: "能力档",
              dataIndex: "profile",
              render: (value: string, record) => (
                <span className="text-xs text-[#4b5563]">
                  {profileLabel(value)}
                  {record.resolutions?.length ? ` · ${record.resolutions.join("/")}` : ""}
                </span>
              ),
            },
            {
              title: "默认",
              dataIndex: "is_default",
              width: 88,
              render: (_, record) => (
                <Switch
                  checked={record.is_default}
                  onChange={(checked) => updateModel(record.workflow_id, { is_default: checked, enabled: checked ? true : record.enabled })}
                />
              ),
            },
          ]}
        />
      </section>

      <Modal
        title="添加生图模型"
        open={addOpen}
        onCancel={() => setAddOpen(false)}
        onOk={() => addModel.mutate()}
        confirmLoading={addModel.isPending}
        okText="添加"
        destroyOnHidden
      >
        <div className="space-y-3 pt-1">
          <div>
            <label className="block text-xs font-medium text-[#4b5563]">上游模型 ID</label>
            <Input className="mt-1.5" value={newModelId} onChange={(event) => setNewModelId(event.target.value)} placeholder="nano-banana-2" />
          </div>
          <div>
            <label className="block text-xs font-medium text-[#4b5563]">显示名称</label>
            <Input className="mt-1.5" value={newDisplayName} onChange={(event) => setNewDisplayName(event.target.value)} placeholder="Nano Banana 2" />
          </div>
          <div>
            <label className="block text-xs font-medium text-[#4b5563]">能力档</label>
            <Select
              className="mt-1.5 w-full"
              value={newProfile}
              onChange={setNewProfile}
              options={catalogQuery.data?.profiles ?? []}
            />
          </div>
        </div>
      </Modal>
    </main>
  )
}
